---
name: Shell commands

on: [push]

jobs:
   run-shell-command:
      runs-on: ubuntu-latest
      steps: 
         - name: echo a string
           run: echo "Hello world of Actions Workflows"
         - name: multiline script
           run: |
              echo "this is a multirun Script step"
              node -v
              npm -v
              which echo

